import { Octokit } from "@octokit/rest";
import { execSync } from 'child_process';
import path from 'path';

class PRService {
    constructor(token) {
        this.octokit = new Octokit({ auth: token });
    }

    async createPatchAndPR(repoPath, repoOwner, repoName, branchName) {
        const options = { cwd: repoPath };

        try {
            console.log(` Creating new branch: ${branchName}`);

            execSync(`git checkout -b ${branchName}`, options);


            execSync('git add .', options);
            execSync('git commit -m "Fix: Security vulnerability patched by Web Patcher"', options);


            console.log(` Pushing to GitHub...`);
            execSync(`git push origin ${branchName}`, options);


            console.log(` Opening Pull Request...`);
            const { data: pr } = await this.octokit.pulls.create({
                owner: repoOwner,
                repo: repoName,
                title: " Security Patch: Fix found by ZAP",
                head: branchName,
                base: "main",
                body: "This is an automated security patch generated by Web Patcher AI. Please review the changes."
            });

            console.log(` PR Created Successfully: ${pr.html_url}`);
            return pr.html_url;

        } catch (error) {
            console.error(" PR Process Failed:", error.message);
            throw error;
        }
    }
}

export default PRService;