import { useState, useMemo, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion as Motion, AnimatePresence } from "framer-motion";
import { Sparkles, ShieldOff } from "lucide-react";
import { getScanRecommendations } from "../../../utils/http/scanRecommendations";
import RecommendationCard from "./RecommendationCard";
import FilterPill from "../FilterPill";
import {
  LIST_VARIANTS,
  RISK_COLORS,
  SEVERITY_FILTER,
} from "../../../data/constants";
import SkeletonCard from "./SkeletonCard";

export default function RecommendationsPanel({
  scanId,
  csrfToken,
  onCountReady,
}) {
  const [riskFilter, setRiskFilter] = useState("All");

  const { data, isPending, error } = useQuery({
    queryKey: ["recommendations", scanId],
    queryFn: () => getScanRecommendations({ csrfToken, scanId }),
  });

  const recommendations = useMemo(() => data?.recommendations ?? [], [data]);
  const recsCount = useMemo(() => data?.count ?? 0, [data]);

  useEffect(() => {
    if (!isPending && !error && onCountReady) {
      onCountReady(recsCount);
    }
  }, [isPending, error, recsCount, onCountReady]);

  const filtered = useMemo(() => {
    if (riskFilter === "All") return recommendations;
    return recommendations.filter((r) => r.risk_level === riskFilter);
  }, [recommendations, riskFilter]);

  // Summary counts by risk level
  const counts = useMemo(() => {
    return recommendations.reduce((acc, r) => {
      acc[r.risk_level] = (acc[r.risk_level] || 0) + 1;
      return acc;
    }, {});
  }, [recommendations]);

  return (
    <Motion.div className="space-y-6 mt-2">
      {/* Section Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 px-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-violet-500/15 border border-violet-500/25">
            <Sparkles size={20} className="text-violet-400" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-white leading-none">
              AI Recommendations
            </h2>
            <p className="text-xs text-gray-400 mt-0.5">
              Generated by{" "}
              <span className="font-bold text-primary-100">WebPatcher</span> AI
              for each critical vulnerability detected
            </p>
          </div>
          {!isPending && recsCount > 0 && (
            <Motion.span
              initial={{ scale: 0.5, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{
                type: "spring",
                stiffness: 400,
                damping: 20,
                delay: 0.8,
              }}
              className="ml-2 flex items-center justify-center px-2.5 py-0.5 rounded-full bg-gradient-to-br from-violet-500/20 to-primary-400 border border-violet-400/30 text-white text-xs font-bold shadow-[0_0_12px_-2px_rgba(139,92,246,0.4)] backdrop-blur-sm"
            >
              {recsCount}
            </Motion.span>
          )}
        </div>

        {/* Risk summary pills */}
        {!isPending && recsCount > 0 && (
          <div className="flex flex-wrap gap-2 text-xs">
            {Object.entries(counts).map(([level, count]) => (
              <span
                key={level}
                className={`px-3 py-1 rounded-full border font-medium ${RISK_COLORS[level]}`}
              >
                {level}: {count}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Loading */}
      {isPending && (
        <div className="space-y-4 px-4">
          {[1, 2, 3].map((i) => (
            <SkeletonCard key={i} />
          ))}
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="mx-4 px-5 py-4 rounded-2xl border border-red-700/30 bg-red-950/30 text-sm text-red-400 flex items-center gap-3">
          <ShieldOff size={18} className="shrink-0" />
          <span>Could not load recommendations: {error.message}</span>
        </div>
      )}

      {/* Content */}
      {!isPending && !error && (
        <>
          {recsCount === 0 ? (
            // Empty state
            <Motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ type: "spring" }}
              className="flex flex-col items-center justify-center gap-4 text-center"
            >
              <div className="p-5 rounded-full bg-gray-800/60 border border-gray-700/50">
                <ShieldOff size={32} className="text-gray-500" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-white opacity-60">
                  No AI recommendations yet
                </h3>
                <p className="text-xs text-gray-500 mt-1 max-w-xs">
                  Recommendations are generated automatically after the AI
                  analysis pipeline processes each vulnerability.
                </p>
              </div>
            </Motion.div>
          ) : (
            <>
              {/* Filter pills bar */}
              <div className="flex items-center gap-2 flex-wrap px-4">
                {SEVERITY_FILTER.map((level) => (
                  <FilterPill
                    key={level}
                    active={riskFilter === level}
                    onClick={() =>
                      setRiskFilter((p) => (p === level ? "All" : level))
                    }
                  >
                    {level}
                    {level !== "All" && counts[level] ? (
                      <span className="ml-1 opacity-60">({counts[level]})</span>
                    ) : null}
                  </FilterPill>
                ))}
              </div>

              {/* Cards list */}
              <AnimatePresence mode="popLayout">
                {filtered.length > 0 ? (
                  <Motion.div
                    key={riskFilter}
                    variants={LIST_VARIANTS}
                    initial="hidden"
                    animate="visible"
                    className="space-y-4 px-4"
                  >
                    {filtered.map((rec, i) => (
                      <RecommendationCard key={i} rec={rec} index={i} />
                    ))}
                  </Motion.div>
                ) : (
                  <Motion.div
                    key="no-match"
                    initial={{ opacity: 0, y: 24 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -24 }}
                    transition={{ type: "spring", stiffness: 60 }}
                    className="text-center py-12 text-gray-500 text-sm"
                  >
                    No{" "}
                    <span className="font-semibold text-primary-100">
                      {riskFilter}
                    </span>{" "}
                    recommendations found.
                  </Motion.div>
                )}
              </AnimatePresence>
            </>
          )}
        </>
      )}
    </Motion.div>
  );
}
